### ISSUE TITLE
Лишний код

### ISSUE THREAD

**Issue by amateomi** [IvanGrigorik/BSUIR_labs#21]
https://github.com/IvanGrigorik/BSUIR_labs/blob/95adf384f040c9ddab55e1c2db7823d5af4e5d7d/5_term/TOKS/lab1/writer/main.py#L9-L10

В API есть уже готовый лист с частотами: https://pyserial.readthedocs.io/en/latest/pyserial_api.html#serial.Serial.BAUDRATES

**Comment by IvanGrigorik** [comment]
Thanks
