### ISSUE TITLE
ТРиТПО крипта

### ISSUE THREAD

**Issue by amateomi** [IvanGrigorik/BSUIR_labs#27]
Среди [бизнес-требований](https://github.com/IvanGrigorik/BSUIR_labs/blob/5_term/5_term/TRITPO/lab2/Requirements.md#business_requirements) не указана криптовалюта, однако при прочтении [отдельного файла](https://github.com/IvanGrigorik/BSUIR_labs/blob/5_term/5_term/TRITPO/lab2/Requirements/overview_of_analogues.md), можно предположить, что в вашем приложении будет данный функционал.

Предлагаю явно это указать.

**Comment by IvanGrigorik** [comment]
Спасибо. Мы не думали, что это непонятно.
