### ISSUE TITLE
ТРиТПО непонятный пункт

### ISSUE THREAD

**Issue by amateomi** [IvanGrigorik/BSUIR_labs#28]
Данный пункт непонятен. О каком ограничении на какие места идет речь?

https://github.com/IvanGrigorik/BSUIR_labs/blob/3e125a14bd66636a404ce81e6fb3402f4be22315/5_term/TRITPO/lab2/Requirements.md?plain=1#L163

**Comment by Joposhnick** [comment]
На мой взгляд это придирка. Речь о местах под уведомления, чтобы не засорять пользователю ленту

**Comment by IvanGrigorik** [comment]
Изменено. Под "уведомлениями" имелось в виду "course alerts", т.е. уведомления о уведомлении конкретной цены валюты на какой-либо момент.
