### ISSUE TITLE
Важно не то, что ты считаешь важным, а то, что считает важным Глецевич

### ISSUE THREAD

**Issue by amateomi** [IvanGrigorik/BSUIR_labs#33]
Ты формируешь [ответы](
https://github.com/IvanGrigorik/BSUIR_labs/blob/2f41ad55c87fcf54fd173f9ffe3d3eebe4b9cbe5/5_term/TOKS/Exam/Answers.pdf) основываясь на сухом тексте со студпаблика, однако не знаешь, что из данной информации стоит обязательно добавлять в ответ. Мне кажется, что ОБЯЗАТЕЛЬНО в ответе должно быть то, что в презентациях Глецевича находится на слайдах с розовой рамкой.

**Comment by IvanGrigorik** [comment]
Т.к. 8 из 10 рамок помечены "важным", я выделяю то, что считаю самым важным в заданном вопросе
